---

# - import_playbook: setup-jumpbox.yml

# - import_playbook: playbooks/manage-flavors.yml
#  import_playbook: playbooks/manage-images.yml
- name: Setup keypairs - ssh keys
  import_playbook: playbooks/manage-keypairs.yml

#- import_playbook: playbooks/manage-networks.yml
#- import_playbook: playbooks/manage-security-groups.yml
#- import_playbook: playbooks/manage-servers.yml

# - import_playbook: playbooks/manage-servers-example.yml

...
